// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqgdwleuigefoctkbjjv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxZ2R3bGV1aWdlZm9jdGtiamp2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxMDY4NTAsImV4cCI6MjA3MDY4Mjg1MH0.aUbxxU7fsKxL1tG9l0k7VOaaOHvTIuviBUfr4wL97Jg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});